name: Deploy with Docker

on:
  push:
    branches:
      - dev  # Überwache nur Pushes in den dev-Branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker
        run: |
          git pull origin dev
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d