name: Deploy with Docker

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Use existing repository
        run: |
          cd /var/opt/Odyss.AI
          git pull origin dev
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up -d